language: node_js
node_js:
- node
addons:
  ssh_known_hosts:
  - "${HOST}"
  apt:
    update: true
    packages:
    - sshpass
before_script:
- chmod +x ./deploy.sh
script: "./deploy.sh"
before_install:
- openssl aes-256-cbc -K $encrypted_cf91a429eecb_key -iv $encrypted_cf91a429eecb_iv
  -in .travis/id_rsa.enc -out .travis/id_rsa -d
